import React, { useContext, useState, useEffect } from 'react';
import { AnalyticsContext } from '../App';
import ChartViewer from '../components/ChartViewer';
import LoadingSpinner from '../components/LoadingSpinner';

const Visualizations = () => {
  const { trainResult, selectedMatch, selectedTeam } = useContext(AnalyticsContext);
  const [advancedCharts, setAdvancedCharts] = useState(null);
  const [loadingAdvanced, setLoadingAdvanced] = useState(false);

  useEffect(() => {
    const fetchAdvancedVisualizations = async () => {
      if (selectedMatch && selectedTeam) {
        setLoadingAdvanced(true);
        try {
          const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';
          const response = await fetch(`${API_URL}/api/visualizations/advanced/${selectedMatch.match_id}/${selectedTeam}`);
          if (response.ok) {
            const data = await response.json();
            setAdvancedCharts(data);
          }
        } catch (error) {
          console.error("Failed to load advanced visualizations", error);
        } finally {
          setLoadingAdvanced(false);
        }
      }
    };

    // Only fetch when trainResult is present to assume data is loaded/cached
    if (trainResult) {
       fetchAdvancedVisualizations();
    }
  }, [trainResult, selectedMatch, selectedTeam]);

  const chartsConfig = [
    { id: 'pressing_heatmap', title: 'Pressing Heatmap', desc: 'Spatial distribution of all pressing actions.' },
    { id: 'defensive_heatmap', title: 'Defensive Heatmap', desc: 'Tackles, interceptions, and clearances.' },
    { id: 'pass_network', title: 'Pass Network', desc: 'Average passing positions and combinations.' },
    { id: 'shot_map', title: 'Shot Map', desc: 'Shot locations sized by expected goals (xG).' },
    { id: 'player_touchmap', title: 'Player Touch Map', desc: 'Activity map for the player with most touches.' },
    { id: 'feature_importance', title: 'Feature Importance', desc: 'Top drivers of pressing success (static).' },
    { id: 'recovery_heatmap', title: 'Recovery Heatmap', desc: 'Locations of all ball recoveries.' },
    { id: 'zone_control_map', title: 'Zone Control Map', desc: 'Relative passing dominance per pitch zone.' },
    { id: 'progressive_pass_map', title: 'Progressive Passes', desc: 'Passes moving the ball 25% closer to goal.' },
    { id: 'tactical_occupancy_map', title: 'Tactical Occupancy', desc: 'Overall touch density divided into 25 zones.' },
    { id: 'expected_threat_map', title: 'Expected Threat (xT)', desc: 'Grid showing forward progression generated by passes.' },
    { id: 'possession_flow_map', title: 'Possession Flow', desc: 'Average pass trajectories showing flow direction.' },
    { id: 'team_shape_map', title: 'Team Shape', desc: 'Convex hull of average player positions.' },
    { id: 'formation_overlay_map', title: 'Formation Overlay', desc: 'Player average positions mapped to grid.' },
    { id: 'defensive_block_map', title: 'Defensive Block Height', desc: 'Average depth of opposition actions when team is out of possession.' },
  ];

  return (
    <div className="p-8 max-w-7xl mx-auto">
      <header className="mb-8">
        <h1 className="text-3xl font-bold font-barlow text-white tracking-wide">Spatial Visualizations</h1>
        <p className="text-[var(--text-muted)] mt-1">Generated using mplsoccer based on StatsBomb event data</p>
      </header>

      {loadingAdvanced ? (
        <div className="flex flex-col items-center justify-center p-12 space-y-4">
            <LoadingSpinner size="large" />
            <p className="text-[var(--accent)] font-bold tracking-widest font-barlow animate-pulse">GENERATING ADVANCED VISUALIZATIONS...</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
          {chartsConfig.map(config => {
            const url = trainResult?.charts?.[config.id] || advancedCharts?.[config.id];
            return (
              <ChartViewer
                key={config.id}
                title={config.title}
                description={config.desc}
                imageUrl={url}
              />
            );
          })}
        </div>
      )}
    </div>
  );
};

export default Visualizations;
