"""Add MatchAnalytics

Revision ID: 1e57c8d9e2a0
Revises: b7b949c28990
Create Date: 2024-06-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e57c8d9e2a0'
down_revision = 'b7b949c28990'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('total_passes', sa.Integer(), nullable=True),
    sa.Column('completed_passes', sa.Integer(), nullable=True),
    sa.Column('pass_completion_rate', sa.Integer(), nullable=True),
    sa.Column('total_shots', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('press_success_rate', sa.Integer(), nullable=True),
    sa.Column('total_pressures', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_analytics_id'), 'match_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_match_analytics_match_id'), 'match_analytics', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_analytics_team_name'), 'match_analytics', ['team_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_analytics_team_name'), table_name='match_analytics')
    op.drop_index(op.f('ix_match_analytics_match_id'), table_name='match_analytics')
    op.drop_index(op.f('ix_match_analytics_id'), table_name='match_analytics')
    op.drop_table('match_analytics')
    # ### end Alembic commands ###
